INFO     root:test_address_dispose.py:31 --------正在执行新增收货地址操作！ --------
INFO     root:common_driver.py:42 -------当前浏览器是：chrome-------
INFO     root:common_driver.py:55 -------重新置空driver-------
WARNING  urllib3.connectionpool:connectionpool.py:811 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DCA5D95CC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/d9a9b03eb17f8957ff26759aa9304224/element
WARNING  urllib3.connectionpool:connectionpool.py:811 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DCA5DA6688>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/d9a9b03eb17f8957ff26759aa9304224/element
WARNING  urllib3.connectionpool:connectionpool.py:811 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DCA5DA6E48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/d9a9b03eb17f8957ff26759aa9304224/element
INFO     root:test_address_dispose.py:31 --------正在执行新增收货地址操作！ --------
INFO     root:common_driver.py:42 -------当前浏览器是：chrome-------
INFO     root:common_driver.py:55 -------重新置空driver-------
WARNING  urllib3.connectionpool:connectionpool.py:811 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DCA6132B08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/746e2b70cbfd54275ee0646d244f7940/element
WARNING  urllib3.connectionpool:connectionpool.py:811 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DCA6136E88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/746e2b70cbfd54275ee0646d244f7940/element
WARNING  urllib3.connectionpool:connectionpool.py:811 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DCA61E4C88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/746e2b70cbfd54275ee0646d244f7940/element
INFO     root:test_address_dispose.py:31 --------正在执行新增收货地址操作！ --------
INFO     root:common_driver.py:42 -------当前浏览器是：chrome-------
INFO     root:common_driver.py:55 -------重新置空driver-------
WARNING  urllib3.connectionpool:connectionpool.py:811 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DCA6182508>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4021b3d213669145ba7ed896849923f1/element
WARNING  urllib3.connectionpool:connectionpool.py:811 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DCA5FBDF48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4021b3d213669145ba7ed896849923f1/element
WARNING  urllib3.connectionpool:connectionpool.py:811 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DCA5D52608>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4021b3d213669145ba7ed896849923f1/element